apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  PORT: "3001"
  NODE_ENV: "production"
  FLASK_ENV: "production"
  RABBIT_URL: "amqp://guest:guest@rabbitmq.ecommerce.svc.cluster.local:5672"
  MONGODB_URL: "mongodb://mongodb.ecommerce.svc.cluster.local:27017"
  POSTGRES_HOST: "postgresql.ecommerce.svc.cluster.local"
  POSTGRES_USER: "admin"
  POSTGRES_DB: "ecommerce"
  KONG_HOST: "kong.ecommerce.svc.cluster.local"
  KONG_PORT: "8000"
